/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Project.FinalProject;

import com.mycompany.libraryoperations.Book;
import com.mycompany.libraryoperations.EBook;
import com.mycompany.libraryoperations.Library;
import com.mycompany.libraryoperations.LibraryManagementSystem;
import com.mycompany.libraryoperations.PrintedBook;
import javax.swing.JOptionPane;

/**
 *
 * @author 2393920
 */
public class AddaBook extends javax.swing.JFrame {
    private Library library; //declare method to hold shared library object

    /**
     * Creates new form AddaBook
     */
    public AddaBook(Library sharedLibrary) { //using library where everything is in
        initComponents(); //layout
        
        //hide file size and number of pages until user selects the type of book
        FileSize.setVisible(false); 
        txtFileSize.setVisible(false);
        NumPages.setVisible(false);
        txtNumPages.setVisible(false);
        
        setVisible(true); //add book window visible
        this.library = sharedLibrary; //saves passed shared library
        
        this.setLocation(650,350);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        FillOutPgaeToAddBook = new javax.swing.JLabel();
        TitleOfBook = new javax.swing.JLabel();
        txtTitleOfBook = new javax.swing.JTextField();
        PrintedBook = new javax.swing.JCheckBox();
        CjeckOptionBestApplies = new javax.swing.JLabel();
        EBook = new javax.swing.JCheckBox();
        NameOfAuthor = new javax.swing.JLabel();
        txtNameOfAuthor = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        FileSize = new javax.swing.JLabel();
        NumPages = new javax.swing.JLabel();
        txtFileSize = new javax.swing.JTextField();
        txtNumPages = new javax.swing.JTextField();
        ISBN = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FillOutPgaeToAddBook.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        FillOutPgaeToAddBook.setText("Please fill out this page to add a book, save when done :");
        FillOutPgaeToAddBook.setEnabled(false);

        TitleOfBook.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TitleOfBook.setText("Title of book:");

        buttonGroup1.add(PrintedBook);
        PrintedBook.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        PrintedBook.setText("Printed Book");
        PrintedBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintedBookActionPerformed(evt);
            }
        });

        CjeckOptionBestApplies.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        CjeckOptionBestApplies.setText("Check which option best applies:");

        buttonGroup1.add(EBook);
        EBook.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        EBook.setText("EBook");
        EBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EBookActionPerformed(evt);
            }
        });

        NameOfAuthor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        NameOfAuthor.setText("Name of author:");

        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });

        Save.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        FileSize.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        FileSize.setText("File size");
        jPanel1.add(FileSize);
        FileSize.setBounds(10, 10, 60, 16);

        NumPages.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        NumPages.setText("Number of pages");
        jPanel1.add(NumPages);
        NumPages.setBounds(10, 10, 100, 18);

        txtFileSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileSizeActionPerformed(evt);
            }
        });
        jPanel1.add(txtFileSize);
        txtFileSize.setBounds(120, 10, 310, 22);

        txtNumPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPagesActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumPages);
        txtNumPages.setBounds(120, 10, 310, 22);

        ISBN.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ISBN.setText("ISBN:");

        Back.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CjeckOptionBestApplies)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PrintedBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EBook)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TitleOfBook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(txtTitleOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(NameOfAuthor)
                                .addGap(25, 25, 25)
                                .addComponent(txtNameOfAuthor)))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(FillOutPgaeToAddBook))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ISBN)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(FillOutPgaeToAddBook)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitleOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleOfBook))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CjeckOptionBestApplies)
                    .addComponent(PrintedBook)
                    .addComponent(EBook))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNameOfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameOfAuthor)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ISBN)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Back))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintedBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintedBookActionPerformed
        // TODO add your handling code here:
        
        //hides EBook field:
        FileSize.setVisible(false); 
        txtFileSize.setVisible(false);
        
        //when select printed book, number of pages is shown to fill out and not file size
        NumPages.setVisible(true);
        txtNumPages.setVisible(true);
    }//GEN-LAST:event_PrintedBookActionPerformed

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void txtNumPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPagesActionPerformed

    private void txtFileSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileSizeActionPerformed

    private void EBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EBookActionPerformed
        // TODO add your handling code here:
        
        //show file size field
        FileSize.setVisible(true);
        txtFileSize.setVisible(true);
        
        //hides printed book field
        NumPages.setVisible(false);
        txtNumPages.setVisible(false);
    }//GEN-LAST:event_EBookActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(); //goes back to main GUI
        menu.setVisible(true);  //shows menu
        this.dispose(); //closes current add book window

    }//GEN-LAST:event_BackActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        //getting user input:
        String title = txtTitleOfBook.getText();
        String author = txtNameOfAuthor.getText();
        String isbn = txtISBN.getText();
        
        //create book object, being either printed book or EBook:
        Book book = null; //initializing book vaiable
        
        //if printedBook is checked:
        if(PrintedBook.isSelected()){
            //parse pages normally:
            int pages;
            try{
                //try to convert input text to int for num pages:
                pages = Integer.parseInt(txtNumPages.getText()); 
            } catch(Exception e){
                //error message if not valid number:
                JOptionPane.showMessageDialog(this, "Pages have to be a number please");
                return; //exits save method
            }
            
            //creates aprinted book object with input values:
            book = new PrintedBook(title, author, isbn, pages);
            
            //if EBook checkbox is selected:
            }else if (EBook.isSelected()){
            //parse fileSize now not pages:
            double fileSize;
            try{
                // Try to convert input text to a double for file size
                fileSize = Double.parseDouble(txtFileSize.getText()); //ensure double input
            } catch (Exception e){
                //error
                JOptionPane.showMessageDialog(this, "File size has to be a number");
                return; //exits
            }
            //creates EBook object with input values:
           book = new EBook(title, author, isbn, fileSize);
           //if no book type is selected:
        }else{
            JOptionPane.showMessageDialog(this, "Please select a book type");
            return;
        }
        
        //saving book object to book.ser(serialization)library and add:
        boolean added = Library.getInstance().addBook(book);
        boolean saved = Library.getInstance().saveBooks("books.ser");

        //success or error message:
        if(added && saved){
            JOptionPane.showMessageDialog(this, "Book saved successfully");       
        }else {
           JOptionPane.showMessageDialog(this, "Book saved unsuccessfully"); 
        }
 //*/       
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddaBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddaBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddaBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddaBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddaBook().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel CjeckOptionBestApplies;
    private javax.swing.JCheckBox EBook;
    private javax.swing.JLabel FileSize;
    private javax.swing.JLabel FillOutPgaeToAddBook;
    private javax.swing.JLabel ISBN;
    private javax.swing.JLabel NameOfAuthor;
    private javax.swing.JLabel NumPages;
    private javax.swing.JCheckBox PrintedBook;
    private javax.swing.JButton Save;
    private javax.swing.JLabel TitleOfBook;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFileSize;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNameOfAuthor;
    private javax.swing.JTextField txtNumPages;
    private javax.swing.JTextField txtTitleOfBook;
    // End of variables declaration//GEN-END:variables

    private Library sharedLibrary() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
