/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Project.FinalProject;

import com.mycompany.libraryoperations.Library;
import com.mycompany.libraryoperations.LibraryManagementSystem;

/**
 *
 * @author 2393920
 */
public class Menu extends javax.swing.JFrame {
    
    Library sharedLibrary = new Library(); //created a shared library object, storing/manage books

    /**
     * Creates new form Menu
     */
    
    //constructor called when object of menu is created:
    public Menu() {
        initComponents(); //initialize GUI components
        setVisible(true); //makes window visible
        sharedLibrary.loadBooks(); //loads previous saved book from file into library
        
        this.setLocation(650,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LibrarymanagementSystem = new javax.swing.JLabel();
        Addabook = new javax.swing.JButton();
        RemoveabBook = new javax.swing.JButton();
        DisplayAllBooks = new javax.swing.JButton();
        SearchBookbyTitle = new javax.swing.JButton();
        SearchBookbyAuthor = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        PleaseSelectAnOption = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N

        LibrarymanagementSystem.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        LibrarymanagementSystem.setText("Library Management System");

        Addabook.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Addabook.setText("Add a book");
        Addabook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddabookActionPerformed(evt);
            }
        });

        RemoveabBook.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        RemoveabBook.setText("Remove a Book");
        RemoveabBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveabBookActionPerformed(evt);
            }
        });

        DisplayAllBooks.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        DisplayAllBooks.setText("Display All Books");
        DisplayAllBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllBooksActionPerformed(evt);
            }
        });

        SearchBookbyTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SearchBookbyTitle.setText("Search Book by Title");
        SearchBookbyTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBookbyTitleActionPerformed(evt);
            }
        });

        SearchBookbyAuthor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SearchBookbyAuthor.setText("Search Book by Author");
        SearchBookbyAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBookbyAuthorActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        PleaseSelectAnOption.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PleaseSelectAnOption.setText("Please select an option:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Exit)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LibrarymanagementSystem)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchBookbyAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayAllBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RemoveabBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Addabook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchBookbyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(99, 99, 99))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(PleaseSelectAnOption)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LibrarymanagementSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PleaseSelectAnOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Addabook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveabBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayAllBooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchBookbyTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchBookbyAuthor)
                .addGap(23, 23, 23)
                .addComponent(Exit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose(); //exit gui   
    }//GEN-LAST:event_ExitActionPerformed

    private void SearchBookbyTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookbyTitleActionPerformed
        // TODO add your handling code here:
        SearchBookbyTitle searchTitle = new SearchBookbyTitle(); //creates new window
        searchTitle.setVisible(true); //new window visible
    }//GEN-LAST:event_SearchBookbyTitleActionPerformed

    //when click add book, opens gui and closes menu:
    private void AddabookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddabookActionPerformed
        // TODO add your handling code here:
        
        AddaBook add = new AddaBook(sharedLibrary); //pass shared library to add book window
        add.setVisible(true); //show add book window
        
        this.dispose(); //close menu window
    }//GEN-LAST:event_AddabookActionPerformed

    //when click display books, opens gui and closes menu:
    private void DisplayAllBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllBooksActionPerformed
        // TODO add your handling code here:
        DisplayAllBooks display = new DisplayAllBooks(sharedLibrary); //pass shared library to add book window
        display.setVisible(true); //show display book window
        this.dispose(); //close menu window
    }//GEN-LAST:event_DisplayAllBooksActionPerformed

    //when remove book is clicked, opens it:
    private void RemoveabBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveabBookActionPerformed
        // TODO add your handling code here:
        RemoveaBook remove = new RemoveaBook(sharedLibrary); //open remove books window
        remove.setVisible(true); //show remove gui
    }//GEN-LAST:event_RemoveabBookActionPerformed

    //when search book by author is clicked, opens gui:
    private void SearchBookbyAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookbyAuthorActionPerformed
        // TODO add your handling code here:
        SearchBookbyAuthor searchAuthor = new SearchBookbyAuthor(); //opens search author window
        searchAuthor.setVisible(true); //display gui
    }//GEN-LAST:event_SearchBookbyAuthorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true); //show menu window
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addabook;
    private javax.swing.JButton DisplayAllBooks;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel LibrarymanagementSystem;
    private javax.swing.JLabel PleaseSelectAnOption;
    private javax.swing.JButton RemoveabBook;
    private javax.swing.JButton SearchBookbyAuthor;
    private javax.swing.JButton SearchBookbyTitle;
    // End of variables declaration//GEN-END:variables
}
