/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Project.FinalProject;

import com.mycompany.libraryoperations.Book;
import com.mycompany.libraryoperations.Library;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 2393920
 */

//define class for remove book:
public class RemoveaBook extends javax.swing.JFrame {
    
    //variable holds the shared Library object with all books:
    private Library library;
    
    /**
     * Creates new form RemoveaBook
     */
    
     //Constructor that gets shared library from the Menu:
    public RemoveaBook(Library sharedLibrary) {
        initComponents(); //set up all gui components
        this.library = sharedLibrary; //store shared library
        
        this.setLocation(650,350);
       
     }
    
    //This method sets the content of the JList using data from the sharedLibrary:
    private void setList(Library sharedLibrary){
        
        ArrayList<Book> books = this.library.getBooks(); //gets list of books
        
        //Set custom model to convert book list into list items:
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            
            String[] strings = sharedLibrary.retrieveAllBooks().split("\n"); //Split book list line-by-line
            public int getSize() { return strings.length; } //Return number of items in the list
            public String getElementAt(int i) { return strings[i]; } //retunr book at index i
        });           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChooseBookToRemove = new javax.swing.ButtonGroup();
        RemovingYourBook = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        bookList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RemovingYourBook.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        RemovingYourBook.setText("Removing your Book");

        Back.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnView.setText("View all books");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        bookList.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookList))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(RemovingYourBook))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(btnView)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(RemovingYourBook)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(btnRemove))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(); //create new menu window
        menu.setVisible(true); //show menu
        this.dispose(); //closes current remove book window
    }//GEN-LAST:event_BackActionPerformed

    //called when remove button is clicked:
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        
        int selectedIndex = jList1.getSelectedIndex(); // Get selected index from list
        
        //if book is selected:
    if (selectedIndex != -1) {
        // Get the selected string from JList selected book
        String selectedText = jList1.getSelectedValue();

        // Initialize variable to hold the book to remove
        Book bookToRemove = null;
        
        //Loop through books in the library to find the matching book:
        for (Book book : library.getBooks()) {
            if (book.toString().equals(selectedText)) {
                bookToRemove = book; //store matching book
                break;
            }
        }

        if (bookToRemove != null) {
            boolean removed = library.removeBook(bookToRemove); //attempt to remove book
            if (removed) {
                library.saveBooks(); //save updated list to file
                JOptionPane.showMessageDialog(this, "Book removed successfully."); //success message
                btnView.doClick(); // Refresh the list by clicking view
            } else {
                JOptionPane.showMessageDialog(this, "Failed to remove book."); //error if remove fails
            }
        } else {
            JOptionPane.showMessageDialog(this, "Book not found in the library."); //error if book not found
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a book to remove."); //message if no book is selected
    }
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    //Called when View all books button is clicked:
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        // Split string list to show in GUI, get all books as string:
        String allBooks = library.retrieveAllBooks();
        String[] bookLines = allBooks.split("\n"); //split into array of book strings
        jList1.setListData(bookLines); // Show each book as 1 item individually
        
    }//GEN-LAST:event_btnViewActionPerformed
        
        
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RemoveaBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RemoveaBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RemoveaBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RemoveaBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RemoveaBook().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.ButtonGroup ChooseBookToRemove;
    private javax.swing.JLabel RemovingYourBook;
    private javax.swing.JScrollPane bookList;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnView;
    private javax.swing.JList<String> jList1;
    // End of variables declaration//GEN-END:variables
}
