/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Project.FinalProject;

//import so we can search for books:
import com.mycompany.libraryoperations.Library;

/**
 *
 * @author 2393920
 */
public class SearchBookbyTitle extends javax.swing.JFrame {

    /**
     * Creates new form SearchBookbyTitle
     */
    
    //Constructor runs when the SearchBookbyTitle is created
    public SearchBookbyTitle() {
        initComponents(); //Initialize GUI components
        
        this.setLocation(650,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FindYourBookByTitle = new javax.swing.JLabel();
        EnterTheTitleOfTheBook = new javax.swing.JLabel();
        txtEnterTheTitleOfTheBook = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Find = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FindYourBookByTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        FindYourBookByTitle.setText("Find your Book by Title");

        EnterTheTitleOfTheBook.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        EnterTheTitleOfTheBook.setText("Enter the title of the book:");

        Back.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Find.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Find.setText("Find");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnterTheTitleOfTheBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnterTheTitleOfTheBook)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Find)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(FindYourBookByTitle)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(FindYourBookByTitle)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterTheTitleOfTheBook)
                    .addComponent(txtEnterTheTitleOfTheBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Find)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //called when back buttin is clicked:
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(); //Create new Menu window 
        menu.setVisible(true); //show main menu
        this.dispose(); //closes current window
    }//GEN-LAST:event_BackActionPerformed

    // Called when Find button is clicked:
    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        // TODO add your handling code here:
 
        //Get the title input from user and remove extra spaces:
        String title = txtEnterTheTitleOfTheBook.getText().trim(); //getting user input
        
        //search for book by title, using library:
        String result = Library.getInstance().retrieveBookByTitle(title);
        
        //check found, show result, if found book, shows in text area:
        if(result != null){
            txtResult.setText(result); //show book details
        } else{
            txtResult.setText("Book not found"); //if book not found, error
        }
               
    }//GEN-LAST:event_FindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBookbyTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBookbyTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBookbyTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBookbyTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBookbyTitle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel EnterTheTitleOfTheBook;
    private javax.swing.JButton Find;
    private javax.swing.JLabel FindYourBookByTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEnterTheTitleOfTheBook;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
